language: go
go:
- 1.6.1
env:
  global:
  - SSH_KEY="travis_key"
  - GIT_NAME="Davis Freimanis"
  - GIT_EMAIL="davisfreimanis@gmail.com"
  - SOURCE_DIR="public"
  - DEPLOY_BRANCH="source"
before_install:
- openssl aes-256-cbc -K $encrypted_a8b70c913422_key -iv $encrypted_a8b70c913422_iv
  -in travis_key.enc -out travis_key -d
- chmod +x deploy.sh
script:
- hugo version
- hugo
- ls
install:
- go get -v github.com/spf13/hugo
after_success:
- echo "davisfreimanis.github.io" > ./public/CNAME
- "./deploy.sh"
