baseurl = "https://davisfreimanis.github.io/"
languageCode = "en-us"
title = "Davis Freimanis"
theme = "purehugo"
publishdir = "public"
contentdir = "content"
canonifyurls = true 

[params]
	githubName = "davisfreimanis"
	twitterName = "Davis_Freimanis"